# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./TruckBooking
    
jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      
    - run: cd ~/actions-runner/deploy/loadsApi/loadsApi/TruckBooking
    - run: sudo docker container stop load-container || true
    - run: sudo docker container stop docker-postgres || true
    - run: sudo docker container rm load-container || true
    - run: sudo docker image rm load || true
    - run: sudo docker build -t load .
    - run: sudo docker start docker-postgres || sudo docker run --name docker-postgres -e POSTGRES_ROOT_PASSWORD=postgres -e POSTGRES_DATABASE=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -d postgres
    - run: sudo docker run -p 8080:8080 --name load-container --link docker-postgres:postgres load | echo "success" 
 
